### DISCUSSION TITLE
METviewer docker error: java.lang.NullPointerException

### DISCUSSION THREAD

**Discussion by rvalenzuelar** [dtcenter/METplus#1044] [Plot Generation] [answered]
Greetings,
 
I am following [these instructions](https://www.youtube.com/watch?v=-KrTUzr_xuY) to run METviewer on a Docker container. Everything goes well until I execute:
```bash
/METviewer/bin/mv_load.sh /data/load_spec_file.xml
```
Then, I get the following message:
```bash
[root@29beb81b189a /]# /METviewer/bin/mv_load.sh /data/load_spec_file.xml
----  MVLoad  ----

Version: 4.0.0

Begin time: 2021-07-28 18:47:08
Parsing: /data/load_spec_file.xml

2021-07-28 edu.ucar.metviewer.MVLoad.main(Unknown Source) -1 main -   **  ERROR: Caught class java.lang.NullPointerException: null
java.lang.NullPointerException
----  MVLoad Done  ----
```
This is my xml file:
```xml
<load_spec>

  <connection>
    <host>mysql_mv:3306</host>
    <database>mv_tormenta_enero2021</database>
    <user>root</user>
    <password>mvuser</password>
  </connection>

  <date_list name="folder_dates">
    <start>2021012618</start>
    <end><date_offset><day_offset>4</day_offset><hour>0</hour></date_offset></end>
    <inc>21600</inc>
    <format>yyyyMMddHH</format>
  </date_list>

  <verbose>false</verbose>
  <insert_size>1</insert_size>
  <mode_header_db_check>false</mode_header_db_check>
  <drop_indexes>false</drop_indexes>
  <apply_indexes>true</apply_indexes>
  
  <load_stat>true</load_stat>
  <load_mode>false</load_mode>
  <load_mtd>false</load_mtd>
  <load_mpr>false</load_mpr>

  <folder_tmpl>/data/{valid_time}</folder_tmpl>
  
  <load_val>
    <field name="valid_time">
      <date_list name="folder_dates"/>
    </field>
  </load_val>

</load_spec>
```
These are my env variables:
```bash
export METVIEWER_DATA=`pwd`/output/met_plus/GridStat
export MYSQL_DIR=`pwd`/MySQL
export METVIEWER_DIR=`pwd`/METviewer
export METVIEWER_DOCKER_IMAGE=dtcenter/metviewer
```
This is the docker-compose.yml file:
```yml
db:
    image: mysql:5.7
    container_name: mysql_mv
    user: "mysql:mysql"
    ports:
        - "6603:3306"
    volumes:
        - ${MYSQL_DIR}:/var/lib/mysql

    environment:
        MYSQL_ROOT_PASSWORD: mvuser
    tty: true
#
metviewer:
    image: ${METVIEWER_DOCKER_IMAGE}
    container_name: metviewer_1
    ports:
    - "8080:8080"
    volumes:
      - ${METVIEWER_DATA}:/data
      - ${METVIEWER_DIR}/metviewer_output/xml:/opt/tomcat/webapps/metviewer_output/xml
      - ${METVIEWER_DIR}/metviewer_output/plots:/opt/tomcat/webapps/metviewer_output/plots
      - ${METVIEWER_DIR}/metviewer_output/data:/opt/tomcat/webapps/metviewer_output/data
      - ${METVIEWER_DIR}/metviewer_output/scripts:/opt/tomcat/webapps/metviewer_output/scripts
    links:
      - db:mysql_mv
    tty: true
#
```

Please let me know any extra information you need to diagnose.
